import { DEFAULT_SLIDERS } from "./promptTypes.js";

export const PRESETS = {
  "Balanced Defaults": DEFAULT_SLIDERS,
  "Soft Oracle": {
    Weirdness: 35,
    Darkness: 15,
    Sparkle: 35,
    Softness: 85,
    Mysticism: 65,
    "Childlike wonder": 55,
    Iridescence: 45,
    Bioluminescence: 25,
    "Aura glow": 70,
    Pearlescence: 60,
    "Colour intensity": 45,
    "Sunset warmth": 65,
    "Spectral rim light": 40,
    "Sacred geometry": 35,
    "Floral filigree": 55,
    "Decorative linework": 35,
    "Cosmic symbolism": 35,
    "Nature symbolism": 60,
    "Yoni symbolism": 20,
    "Halo intensity": 60,
    "Ornament density": 35,
    "Negative space": 75,
    "Focal clarity": 85,
    "Background detail": 25,
    "Companion presence": 20,
    "Border decoration": 50,
    Symmetry: 55,
    "Layered depth": 55,
  },
  "Sacred Dream": {
    Weirdness: 60,
    Darkness: 25,
    Sparkle: 45,
    Softness: 75,
    Mysticism: 85,
    "Childlike wonder": 55,
    Iridescence: 65,
    Bioluminescence: 45,
    "Aura glow": 80,
    Pearlescence: 55,
    "Colour intensity": 60,
    "Sunset warmth": 45,
    "Spectral rim light": 65,
    "Sacred geometry": 70,
    "Floral filigree": 45,
    "Decorative linework": 50,
    "Cosmic symbolism": 70,
    "Nature symbolism": 55,
    "Yoni symbolism": 35,
    "Halo intensity": 75,
    "Ornament density": 55,
    "Negative space": 65,
    "Focal clarity": 85,
    "Background detail": 35,
    "Companion presence": 35,
    "Border decoration": 60,
    Symmetry: 70,
    "Layered depth": 70,
  },
  "Inner Child Glow": {
    Weirdness: 45,
    Darkness: 5,
    Sparkle: 55,
    Softness: 90,
    Mysticism: 50,
    "Childlike wonder": 95,
    Iridescence: 70,
    Bioluminescence: 40,
    "Aura glow": 75,
    Pearlescence: 70,
    "Colour intensity": 70,
    "Sunset warmth": 70,
    "Spectral rim light": 45,
    "Sacred geometry": 20,
    "Floral filigree": 65,
    "Decorative linework": 45,
    "Cosmic symbolism": 45,
    "Nature symbolism": 75,
    "Yoni symbolism": 10,
    "Halo intensity": 55,
    "Ornament density": 45,
    "Negative space": 70,
    "Focal clarity": 80,
    "Background detail": 35,
    "Companion presence": 45,
    "Border decoration": 55,
    Symmetry: 35,
    "Layered depth": 55,
  },
  "Cosmic Garden": {
    Weirdness: 70,
    Darkness: 20,
    Sparkle: 65,
    Softness: 70,
    Mysticism: 75,
    "Childlike wonder": 70,
    Iridescence: 85,
    Bioluminescence: 75,
    "Aura glow": 75,
    Pearlescence: 60,
    "Colour intensity": 80,
    "Sunset warmth": 45,
    "Spectral rim light": 70,
    "Sacred geometry": 45,
    "Floral filigree": 80,
    "Decorative linework": 65,
    "Cosmic symbolism": 85,
    "Nature symbolism": 90,
    "Yoni symbolism": 30,
    "Halo intensity": 65,
    "Ornament density": 70,
    "Negative space": 55,
    "Focal clarity": 80,
    "Background detail": 55,
    "Companion presence": 35,
    "Border decoration": 70,
    Symmetry: 45,
    "Layered depth": 80,
  },
  "Velvet Night Healing": {
    Weirdness: 55,
    Darkness: 75,
    Sparkle: 45,
    Softness: 80,
    Mysticism: 80,
    "Childlike wonder": 35,
    Iridescence: 50,
    Bioluminescence: 70,
    "Aura glow": 75,
    Pearlescence: 35,
    "Colour intensity": 50,
    "Sunset warmth": 20,
    "Spectral rim light": 70,
    "Sacred geometry": 45,
    "Floral filigree": 45,
    "Decorative linework": 40,
    "Cosmic symbolism": 75,
    "Nature symbolism": 55,
    "Yoni symbolism": 25,
    "Halo intensity": 70,
    "Ornament density": 45,
    "Negative space": 70,
    "Focal clarity": 85,
    "Background detail": 30,
    "Companion presence": 25,
    "Border decoration": 55,
    Symmetry: 55,
    "Layered depth": 75,
  },
  "Psychedelic Bloom": {
    Weirdness: 85,
    Darkness: 25,
    Sparkle: 75,
    Softness: 65,
    Mysticism: 80,
    "Childlike wonder": 75,
    Iridescence: 95,
    Bioluminescence: 80,
    "Aura glow": 85,
    Pearlescence: 70,
    "Colour intensity": 95,
    "Sunset warmth": 55,
    "Spectral rim light": 85,
    "Sacred geometry": 65,
    "Floral filigree": 85,
    "Decorative linework": 80,
    "Cosmic symbolism": 80,
    "Nature symbolism": 85,
    "Yoni symbolism": 40,
    "Halo intensity": 80,
    "Ornament density": 75,
    "Negative space": 50,
    "Focal clarity": 85,
    "Background detail": 55,
    "Companion presence": 40,
    "Border decoration": 80,
    Symmetry: 50,
    "Layered depth": 85,
  },
};
